var HOTEL_DATA = [
  {
    "name": "广州塔艺术博物院亚朵酒店",
    "city": "广州",
    "district": "海珠",
    "address": "近琶洲会展，步行广州塔，双地铁站。",
    "phone": "",
    "star": "五星",
    "rating": "4.9",
    "reviews": "超棒1,507条点评",
    "price": "653",
    "photoQueen": "",
    "photoTwin": "",
    "transport": []
  },
  {
    "name": "丽呈衡居酒店(广州萝岗店)",
    "city": "广州",
    "district": "黄埔",
    "address": "近万达广场(广州萝岗店) · 宝能演艺中心/天河智慧城",
    "phone": "",
    "star": "五星",
    "rating": "4.9",
    "reviews": "超棒91条点评",
    "price": "177",
    "photoQueen": "",
    "photoTwin": "",
    "transport": []
  },
  {
    "name": "广州高斯酒店(广州塔琶洲会展店)",
    "city": "广州",
    "district": "海珠",
    "address": "近中国进出口商品交易会（广交会）展馆 · 琶洲会展/广州塔/客村",
    "phone": "",
    "star": "五星",
    "rating": "4.9",
    "reviews": "超棒1,092条点评",
    "price": "508",
    "photoQueen": "",
    "photoTwin": "",
    "transport": []
  },
  {
    "name": "广州天河太古汇城际酒店",
    "city": "广州",
    "district": "天河",
    "address": "近天河体育中心 · 正佳广场商贸旅游区",
    "phone": "",
    "star": "五星",
    "rating": "4.8",
    "reviews": "超棒3,181条点评",
    "price": "586",
    "photoQueen": "",
    "photoTwin": "",
    "transport": []
  },
  {
    "name": "全季酒店(广州中大地铁站店)",
    "city": "广州",
    "district": "海珠",
    "address": "毗邻中山大学，近广州塔和琶洲展馆",
    "phone": "",
    "star": "五星",
    "rating": "4.8",
    "reviews": "超棒2,597条点评",
    "price": "365",
    "photoQueen": "",
    "photoTwin": "",
    "transport": []
  },
  {
    "name": "汉庭酒店(广州黄埔萝岗地铁站店)",
    "city": "广州",
    "district": "黄埔",
    "address": "近宝能广州国际体育演艺中心 · 萝岗地铁站",
    "phone": "",
    "star": "五星",
    "rating": "4.8",
    "reviews": "超棒1,083条点评",
    "price": "239",
    "photoQueen": "",
    "photoTwin": "",
    "transport": []
  },
  {
    "name": "广州总统大酒店(天河体育中心太古汇店)",
    "city": "广州",
    "district": "天河",
    "address": "近正佳广场商贸旅游区 · 广州太古汇",
    "phone": "",
    "star": "五星",
    "rating": "4.8",
    "reviews": "超棒8,191条点评",
    "price": "438",
    "photoQueen": "",
    "photoTwin": "",
    "transport": []
  },
  {
    "name": "广州琶洲会展宜致美居",
    "city": "广州",
    "district": "海珠",
    "address": "近琶洲展馆 · 广州塔",
    "phone": "",
    "star": "五星",
    "rating": "4.8",
    "reviews": "超棒2,837条点评",
    "price": "221",
    "photoQueen": "",
    "photoTwin": "",
    "transport": []
  },
  {
    "name": "隐舍酒店(广州江南西昌岗地铁站店)",
    "city": "广州",
    "district": "海珠",
    "address": "近北京路步行街 · 江南西地铁站",
    "phone": "",
    "star": "五星",
    "rating": "4.8",
    "reviews": "超棒8,382条点评",
    "price": "356",
    "photoQueen": "",
    "photoTwin": "",
    "transport": []
  },
  {
    "name": "广州珠江新城太古汇宜致美居",
    "city": "广州",
    "district": "天河",
    "address": "近广州太古汇 · 天河体育中心",
    "phone": "",
    "star": "五星",
    "rating": "4.8",
    "reviews": "超棒14,311条点评",
    "price": "399",
    "photoQueen": "",
    "photoTwin": "",
    "transport": []
  },
  {
    "name": "广州珠江新城太古汇亚朵酒店",
    "city": "广州",
    "district": "天河",
    "address": "近广州太古汇 · 正佳广场商贸旅游区",
    "phone": "",
    "star": "五星",
    "rating": "4.8",
    "reviews": "超棒5,547条点评",
    "price": "568",
    "photoQueen": "",
    "photoTwin": "",
    "transport": []
  },
  {
    "name": "广州北京路步行街美居酒店",
    "city": "广州",
    "district": "越秀",
    "address": "近北京路步行街 · 北京路地铁站",
    "phone": "",
    "star": "五星",
    "rating": "4.8",
    "reviews": "超棒14,285条点评",
    "price": "653",
    "photoQueen": "",
    "photoTwin": "",
    "transport": []
  },
  {
    "name": "广州珠江新城五羊邨地铁站亚朵酒店",
    "city": "广州",
    "district": "天河",
    "address": "近五羊邨地铁站 · 珠江新城/省博物馆",
    "phone": "",
    "star": "五星",
    "rating": "4.8",
    "reviews": "超棒5,101条点评",
    "price": "534",
    "photoQueen": "",
    "photoTwin": "",
    "transport": []
  },
  {
    "name": "广州琶洲会展海珠湿地公园宜致美居",
    "city": "广州",
    "district": "海珠",
    "address": "琶洲会展/广州塔/客村 · 近广州塔",
    "phone": "",
    "star": "五星",
    "rating": "4.8",
    "reviews": "超棒4,303条点评",
    "price": "272",
    "photoQueen": "",
    "photoTwin": "",
    "transport": []
  },
  {
    "name": "广州保利洲际酒店(广州塔琶洲会展中心店)",
    "city": "广州",
    "district": "海珠",
    "address": "阅江中路828号",
    "phone": "020-89668888",
    "star": "五星",
    "rating": "4.8",
    "reviews": "超棒3,689条点评",
    "price": "887",
    "photoQueen": "",
    "photoTwin": "",
    "transport": [
      {"name": "广州白云国际机场", "distance": "42公里", "drive": "约50分钟"},
      {"name": "广州南站", "distance": "18公里", "drive": "约30分钟"},
      {"name": "广州东站", "distance": "12公里", "drive": "约25分钟"}
    ]
  },
  {
    "name": "广州珠江新城假日酒店",
    "city": "广州",
    "district": "天河",
    "address": "近广州塔 · 广东省博物馆",
    "phone": "",
    "star": "五星",
    "rating": "4.8",
    "reviews": "超棒4,972条点评",
    "price": "665",
    "photoQueen": "",
    "photoTwin": "",
    "transport": []
  },
  {
    "name": "全季大观广州塔琶洲会展中心酒店",
    "city": "广州",
    "district": "海珠",
    "address": "近广州国际会展中心 · 中国进出口商品交易会（广交会）展馆",
    "phone": "",
    "star": "五星",
    "rating": "4.8",
    "reviews": "超棒326条点评",
    "price": "671",
    "photoQueen": "",
    "photoTwin": "",
    "transport": []
  },
  {
    "name": "榆漫居酒店(广州太古汇天河体育中心旗舰店)",
    "city": "广州",
    "district": "天河",
    "address": "近广州太古汇 · 天河体育中心",
    "phone": "",
    "star": "五星",
    "rating": "4.8",
    "reviews": "超棒4,557条点评",
    "price": "365",
    "photoQueen": "",
    "photoTwin": "",
    "transport": []
  },
  {
    "name": "广州白云国际会议中心越秀福朋喜来登酒店",
    "city": "广州",
    "district": "越秀",
    "address": "近广州白云国际会议中心 · 广州体育馆",
    "phone": "",
    "star": "五星",
    "rating": "4.8",
    "reviews": "超棒5,347条点评",
    "price": "538",
    "photoQueen": "",
    "photoTwin": "",
    "transport": []
  },
  {
    "name": "广州塔海心桥亚朵酒店",
    "city": "广州",
    "district": "海珠",
    "address": "近琶洲展馆，步抵广州塔，双地铁站旁",
    "phone": "",
    "star": "五星",
    "rating": "4.8",
    "reviews": "超棒620条点评",
    "price": "764",
    "photoQueen": "",
    "photoTwin": "",
    "transport": []
  },
  {
    "name": "广州白云国际机场希尔顿惠庭酒店",
    "city": "广州",
    "district": "白云",
    "address": "白云国际机场附近 · 花都融创文旅城及周边",
    "phone": "",
    "star": "五星",
    "rating": "4.8",
    "reviews": "超棒2,715条点评",
    "price": "359",
    "photoQueen": "",
    "photoTwin": "",
    "transport": []
  },
  {
    "name": "广东迎宾馆",
    "city": "广州",
    "district": "越秀",
    "address": "近北京路步行街 · 越秀公园",
    "phone": "",
    "star": "五星",
    "rating": "4.8",
    "reviews": "超棒5,561条点评",
    "price": "919",
    "photoQueen": "",
    "photoTwin": "",
    "transport": []
  },
  {
    "name": "广州天河体育中心美居酒店",
    "city": "广州",
    "district": "天河",
    "address": "近广州东站 · 天河体育中心",
    "phone": "",
    "star": "五星",
    "rating": "4.8",
    "reviews": "超棒8,462条点评",
    "price": "459",
    "photoQueen": "",
    "photoTwin": "",
    "transport": []
  },
  {
    "name": "广州国际金融城临江大道亚朵见野酒店",
    "city": "广州",
    "district": "天河",
    "address": "近琶洲展馆，广交会豪华巴士免费接送",
    "phone": "",
    "star": "五星",
    "rating": "4.8",
    "reviews": "超棒1,410条点评",
    "price": "560",
    "photoQueen": "",
    "photoTwin": "",
    "transport": []
  },
  {
    "name": "维也纳酒店(广州长隆万达广场万博地铁站店)",
    "city": "广州",
    "district": "番禺",
    "address": "近南村万博地铁站 · 万达广场(广州番禺店)",
    "phone": "",
    "star": "五星",
    "rating": "4.8",
    "reviews": "超棒3,456条点评",
    "price": "259",
    "photoQueen": "",
    "photoTwin": "",
    "transport": []
  },
  {
    "name": "假日无忧酒店(长隆野生动物世界广州南站店)",
    "city": "广州",
    "district": "番禺",
    "address": "近长隆野生动物世界 · 万民城MO CITY(番禺店)",
    "phone": "",
    "star": "五星",
    "rating": "4.8",
    "reviews": "超棒1,164条点评",
    "price": "268",
    "photoQueen": "",
    "photoTwin": "",
    "transport": []
  },
  {
    "name": "宜尚PLUS酒店(广州北京路步行街大佛古寺店)",
    "city": "广州",
    "district": "越秀",
    "address": "近北京路步行街 · 珠江夜游天字码头",
    "phone": "",
    "star": "五星",
    "rating": "4.8",
    "reviews": "超棒4,389条点评",
    "price": "396",
    "photoQueen": "",
    "photoTwin": "",
    "transport": []
  },
  {
    "name": "广州白天鹅宾馆",
    "city": "广州",
    "district": "荔湾",
    "address": "沙面南街1号",
    "phone": "020-81886968",
    "star": "五星",
    "rating": "4.7",
    "reviews": "超棒9,906条点评",
    "price": "1178",
    "photoQueen": "",
    "photoTwin": "",
    "transport": [
      {"name": "广州白云国际机场", "distance": "35公里", "drive": "约45分钟"},
      {"name": "广州南站", "distance": "18公里", "drive": "约30分钟"},
      {"name": "广州东站", "distance": "12公里", "drive": "约25分钟"}
    ]
  },
  {
    "name": "广州天河希尔顿酒店",
    "city": "广州",
    "district": "天河",
    "address": "林和西横路215号",
    "phone": "020-66831888",
    "star": "五星",
    "rating": "4.7",
    "reviews": "超棒11,422条点评",
    "price": "650",
    "photoQueen": "",
    "photoTwin": "",
    "transport": [
      {"name": "广州白云国际机场", "distance": "35公里", "drive": "约45分钟"},
      {"name": "广州南站", "distance": "22公里", "drive": "约35分钟"},
      {"name": "广州东站", "distance": "1公里", "drive": "步行10分钟"}
    ]
  },
  {
    "name": "CityNote希诺轻居(广州北京路步行街南越王博物馆店)",
    "city": "广州",
    "district": "越秀",
    "address": "近北京路步行街 · 农讲所地铁站",
    "phone": "",
    "star": "四星",
    "rating": "4.7",
    "reviews": "超棒2,240条点评",
    "price": "333",
    "photoQueen": "",
    "photoTwin": "",
    "transport": []
  },
  {
    "name": "广州朗豪酒店",
    "city": "广州",
    "district": "海珠",
    "address": "近中国进出口商品交易会（广交会）展馆 · 保利世界贸易中心博览馆",
    "phone": "",
    "star": "四星",
    "rating": "4.7",
    "reviews": "超棒3,208条点评",
    "price": "680",
    "photoQueen": "",
    "photoTwin": "",
    "transport": []
  },
  {
    "name": "丽呈铂锐酒店(广州塔地铁站中山大学店)",
    "city": "广州",
    "district": "海珠",
    "address": "近广州塔 · 珠江夜游",
    "phone": "",
    "star": "四星",
    "rating": "4.7",
    "reviews": "超棒1,386条点评",
    "price": "358",
    "photoQueen": "",
    "photoTwin": "",
    "transport": []
  },
  {
    "name": "广州天河喆啡锐品酒店",
    "city": "广州",
    "district": "天河",
    "address": "近岗顶地铁站 · 广州太古汇",
    "phone": "",
    "star": "四星",
    "rating": "4.7",
    "reviews": "超棒8,507条点评",
    "price": "498",
    "photoQueen": "",
    "photoTwin": "",
    "transport": []
  },
  {
    "name": "枫季(广州新白云国际机场体验店)",
    "city": "广州",
    "district": "白云",
    "address": "近广州白云国际机场 · 晴空便捷(广州新白云国际机场店)",
    "phone": "",
    "star": "四星",
    "rating": "4.7",
    "reviews": "超棒13,526条点评",
    "price": "182",
    "photoQueen": "",
    "photoTwin": "",
    "transport": []
  },
  {
    "name": "创时代酒店(广州天河智慧城地铁站店)",
    "city": "广州",
    "district": "天河",
    "address": "近地铁出行方便，在万科广场吃饭",
    "phone": "",
    "star": "四星",
    "rating": "4.7",
    "reviews": "超棒4,819条点评",
    "price": "194",
    "photoQueen": "",
    "photoTwin": "",
    "transport": []
  },
  {
    "name": "广州华裕万福酒店(广州东站天河体育中心店)",
    "city": "广州",
    "district": "天河",
    "address": "近广州东站 · 华南理工大学(五山校区)",
    "phone": "",
    "star": "四星",
    "rating": "4.7",
    "reviews": "超棒1,903条点评",
    "price": "371",
    "photoQueen": "",
    "photoTwin": "",
    "transport": []
  },
  {
    "name": "宜致酒店(广州长隆野生动物世界店)",
    "city": "广州",
    "district": "番禺",
    "address": "近长隆野生动物世界 · 广州长隆度假区",
    "phone": "",
    "star": "四星",
    "rating": "4.7",
    "reviews": "超棒6,996条点评",
    "price": "338",
    "photoQueen": "",
    "photoTwin": "",
    "transport": []
  },
  {
    "name": "广州珠江新城华轩美仑美奂酒店",
    "city": "广州",
    "district": "天河",
    "address": "近广州塔 · 珠江新城/省博物馆",
    "phone": "",
    "star": "四星",
    "rating": "4.7",
    "reviews": "超棒5,735条点评",
    "price": "653",
    "photoQueen": "",
    "photoTwin": "",
    "transport": []
  },
  {
    "name": "微八逸居公馆(广州永庆坊上下九店)",
    "city": "广州",
    "district": "荔湾",
    "address": "近永庆坊 · 上下九步行街",
    "phone": "",
    "star": "四星",
    "rating": "4.7",
    "reviews": "超棒7,285条点评",
    "price": "391",
    "photoQueen": "",
    "photoTwin": "",
    "transport": []
  },
  {
    "name": "广州丽呈格芮酒店（天河体育中心太古汇店）",
    "city": "广州",
    "district": "天河",
    "address": "近广州太古汇 · 天河体育中心",
    "phone": "",
    "star": "四星",
    "rating": "4.7",
    "reviews": "超棒8,757条点评",
    "price": "539",
    "photoQueen": "",
    "photoTwin": "",
    "transport": []
  },
  {
    "name": "广州粤海喜来登酒店",
    "city": "广州",
    "district": "天河",
    "address": "天河路208号",
    "phone": "020-66688888",
    "star": "五星",
    "rating": "4.7",
    "reviews": "超棒4,240条点评",
    "price": "900",
    "photoQueen": "",
    "photoTwin": "",
    "transport": [
      {"name": "广州白云国际机场", "distance": "36公里", "drive": "约45分钟"},
      {"name": "广州南站", "distance": "21公里", "drive": "约35分钟"},
      {"name": "广州东站", "distance": "3公里", "drive": "约10分钟"}
    ]
  },
  {
    "name": "广州太古汇天河路亚朵酒店",
    "city": "广州",
    "district": "天河",
    "address": "近岗顶地铁站 · 广州太古汇",
    "phone": "",
    "star": "四星",
    "rating": "4.7",
    "reviews": "超棒6,149条点评",
    "price": "526",
    "photoQueen": "",
    "photoTwin": "",
    "transport": []
  },
  {
    "name": "广州白云国际会议中心越秀万豪酒店",
    "city": "广州",
    "district": "越秀",
    "address": "近广州白云国际会议中心 · 广州体育馆",
    "phone": "",
    "star": "四星",
    "rating": "4.7",
    "reviews": "超棒5,193条点评",
    "price": "721",
    "photoQueen": "",
    "photoTwin": "",
    "transport": []
  },
  {
    "name": "花城中心酒店(广州体育中心林和西地铁站店)",
    "city": "广州",
    "district": "天河",
    "address": "地铁口边上，快速直达机场，靠近东站",
    "phone": "",
    "star": "四星",
    "rating": "4.7",
    "reviews": "超棒2,342条点评",
    "price": "302",
    "photoQueen": "",
    "photoTwin": "",
    "transport": []
  },
  {
    "name": "柏高酒店(广州天河城购物中心水荫路店)",
    "city": "广州",
    "district": "天河",
    "address": "近天河体育中心 · 广州东站",
    "phone": "",
    "star": "四星",
    "rating": "4.7",
    "reviews": "超棒2,743条点评",
    "price": "260",
    "photoQueen": "",
    "photoTwin": "",
    "transport": []
  },
  {
    "name": "广州墨寻商务公寓(番禺大道南市南路店)",
    "city": "广州",
    "district": "番禺",
    "address": "近番禺广场 · 天汇百货(太石店)",
    "phone": "",
    "star": "四星",
    "rating": "4.7",
    "reviews": "超棒1,617条点评",
    "price": "137",
    "photoQueen": "",
    "photoTwin": "",
    "transport": []
  },
  {
    "name": "CityNote希诺S酒店 (广州北京路天字码头店)",
    "city": "广州",
    "district": "越秀",
    "address": "近海珠广场地铁站 · 珠江夜游",
    "phone": "",
    "star": "四星",
    "rating": "4.7",
    "reviews": "超棒3,938条点评",
    "price": "358",
    "photoQueen": "",
    "photoTwin": "",
    "transport": []
  },
  {
    "name": "格芮酒店(广州番禺长隆野生动物世界店)",
    "city": "广州",
    "district": "番禺",
    "address": "近长隆野生动物世界 · 广州长隆度假区",
    "phone": "",
    "star": "四星",
    "rating": "4.7",
    "reviews": "超棒2,038条点评",
    "price": "338",
    "photoQueen": "",
    "photoTwin": "",
    "transport": []
  },
  {
    "name": "柏逸酒店(广州珠江新城天河公园地铁站店)",
    "city": "广州",
    "district": "天河",
    "address": "近中国进出口商品交易会（广交会）展馆 · 天河公园地铁站",
    "phone": "",
    "star": "四星",
    "rating": "4.7",
    "reviews": "超棒1,150条点评",
    "price": "209",
    "photoQueen": "",
    "photoTwin": "",
    "transport": []
  },
  {
    "name": "广州东方宾馆",
    "city": "广州",
    "district": "越秀",
    "address": "近越秀公园地铁站 · 广州站",
    "phone": "",
    "star": "四星",
    "rating": "4.7",
    "reviews": "超棒6,793条点评",
    "price": "592",
    "photoQueen": "",
    "photoTwin": "",
    "transport": []
  },
  {
    "name": "丽呈铂锐酒店(长隆野生动物世界广州南站店)",
    "city": "广州",
    "district": "番禺",
    "address": "步行50米可达长隆动物园·美食街",
    "phone": "",
    "star": "四星",
    "rating": "4.7",
    "reviews": "超棒1,624条点评",
    "price": "288",
    "photoQueen": "",
    "photoTwin": "",
    "transport": []
  },
  {
    "name": "维也纳酒店(广州白云国际机场航站楼店)",
    "city": "广州",
    "district": "白云",
    "address": "白云国际机场附近 · 花都融创文旅城及周边",
    "phone": "",
    "star": "四星",
    "rating": "4.7",
    "reviews": "超棒7,777条点评",
    "price": "258",
    "photoQueen": "",
    "photoTwin": "",
    "transport": []
  },
  {
    "name": "迎商酒店(广州北京路步行街公园前地铁站店)",
    "city": "广州",
    "district": "越秀",
    "address": "地理位置优越，距离北京路步行街近",
    "phone": "",
    "star": "四星",
    "rating": "4.7",
    "reviews": "超棒4,766条点评",
    "price": "294",
    "photoQueen": "",
    "photoTwin": "",
    "transport": []
  },
  {
    "name": "城迹酒店(广州正佳太古汇石牌桥地铁站店)",
    "city": "广州",
    "district": "天河",
    "address": "近正佳广场商贸旅游区 · 天河体育中心",
    "phone": "",
    "star": "四星",
    "rating": "4.7",
    "reviews": "超棒3,500条点评",
    "price": "316",
    "photoQueen": "",
    "photoTwin": "",
    "transport": []
  },
  {
    "name": "广州太古汇丽呈睿轩酒店(岗顶地铁站店)",
    "city": "广州",
    "district": "天河",
    "address": "近广州太古汇 · 岗顶地铁站",
    "phone": "",
    "star": "四星",
    "rating": "4.7",
    "reviews": "超棒4,153条点评",
    "price": "293",
    "photoQueen": "",
    "photoTwin": "",
    "transport": []
  },
  {
    "name": "广州亚米智享公寓(番禺亚运城店)",
    "city": "广州",
    "district": "番禺",
    "address": "近石楼牌坊 · 亚运城综合体育馆",
    "phone": "",
    "star": "四星",
    "rating": "4.7",
    "reviews": "超棒132条点评",
    "price": "121",
    "photoQueen": "",
    "photoTwin": "",
    "transport": []
  },
  {
    "name": "塔畔国际公寓(广州塔店)",
    "city": "广州",
    "district": "海珠",
    "address": "近广州塔 · 中山大学(广州校区南校园)",
    "phone": "",
    "star": "四星",
    "rating": "4.7",
    "reviews": "超棒2,143条点评",
    "price": "379",
    "photoQueen": "",
    "photoTwin": "",
    "transport": []
  },
  {
    "name": "鼎舍酒店(广州沙面岛永庆坊店)",
    "city": "广州",
    "district": "荔湾",
    "address": "近北京路步行街 · 沙面",
    "phone": "",
    "star": "四星",
    "rating": "4.7",
    "reviews": "超棒3,366条点评",
    "price": "442",
    "photoQueen": "",
    "photoTwin": "",
    "transport": []
  },
  {
    "name": "广州番禺温德姆花园酒店",
    "city": "广州",
    "district": "番禺",
    "address": "近长隆欢乐世界 · 长隆水上乐园",
    "phone": "",
    "star": "四星",
    "rating": "4.7",
    "reviews": "超棒2,595条点评",
    "price": "438",
    "photoQueen": "",
    "photoTwin": "",
    "transport": []
  }
];